=== carlesmarmol/TTHub/ejemplo-2-DTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Este documento es una DTD (Document Type Definition) muy sencilla.Cuando trabajemos con TEI no usaremos las DTD, sino un tipo de esquema diferente. 
Aún así es interesante que sepáis qué forma tiene este tipo de documento, pues es muy usado en el terreno de la informática y de las aplicaciones XML. -->

<!ELEMENT curso (metadatos,contenido)>
<!-- En una DTD todos los elementos deben ser declarados con el elemento <!ELEMENT...>. Entre paréntesis se indican los elementos descendientes que puede contener -->

<!ELEMENT metadatos (titulo,fecha,profesor+,universidad?)>
<!-- El símbolo + al lado del nombre de un elemento indica que dicho elemento puede aparecer más de una o más de una vez -->
<!-- El interrogante, en cambio, indica que el elemento es optativo, es decir, que puede o no aparecer -->

<!ELEMENT contenido (tema)+>

<!ELEMENT titulo (#PCDATA)>
<!-- (#PCDATA) significa que el contenido del elemento, en este caso del <titulo>, será solo texto.  -->

<!ELEMENT fecha (#PCDATA)>

<!ATTLIST fecha
 cuando NMTOKEN #REQUIRED>
<!-- Con ATTLIST se indica la lista de los atributos. En este caso, hemos añadido un solo atributo que proporciona la fecha en un formato normalizado de manera
que pueda ser interpretada por el ordenador."NMTOKEN" (name token) significa que el valor de dicho atributo solo acepta los caracteres válidos para nombrar cosas en 
XML (letras, números, puntos, guiones, dos puntos). En fin, "#REQUIRED" indica que es un atributo obligatorio. -->

<!ELEMENT profesor (nombre?,apellido+)>

<!ELEMENT universidad (#PCDATA)>


<!ELEMENT tema (titulo?, parrafo)+>

<!ATTLIST tema
  n CDATA #REQUIRED>
  <!-- En esta lista de los atributos del elemento <tema> se indica que debe aparecer obligatoriamente un atributo "n" (número) 
  que como valor debe contener CDATA (character data), cualquier caracter textual.  -->

<!ELEMENT nombre (#PCDATA)>


<!ELEMENT apellido (#PCDATA)>


<!ELEMENT parrafo (#PCDATA)>

=== carlesmarmol/TTHub/L2_ejemplo-2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- ¡esto es un comentario! -->
<!-- En primer lugar aparece la "Declaración XML" -->

<!DOCTYPE curso SYSTEM "ejemplo-2-DTD.dtd">
<!-- "Declaración de Tipo de Documento": DOCTYPE nos está indicando el tipo de documento con el que debe relacionarse este fichero XML, es decir, donde encontramos el modelo que debemos utilizar para
marcar este texto. "curso" indica el elemento raíz, mientras que "SYSTEM" nos indica, en este caso, que el modelo se halla en nuestro sistema y que el modelo en 
cuestión se llama "ejemplo_DTD.dtd" que se halla en la misma carpeta. -->

<?xml-stylesheet href= “formato.css” type= “text/css”?>
<!-- Esto es una "Instrucción de procesamiento" que indica al procesador que este documento XML va asociado a una hoja de estilo CSS que se llamaría formato.css
    y que se encontraría en la misma carpeta.-->

<curso> <!-- "Elemento raíz" -->
    <metadatos>
        <titulo>Introducción a la edición digital de textos: TEI-XML</titulo>
        <fecha cuando="2019-01-22">22 enero 2018</fecha>
        <profesor>
            <nombre>Susanna</nombre>
            <apellido>Allés</apellido>
            <apellido>Torrent</apellido>
        </profesor>
        <universidad>UNED</universidad>
    </metadatos>
    <contenido>
        <tema n="1">
            <titulo>TEMA 1: ¿Qué es la Text Encoding Initiative y qué aplicaciones prácticas tiene?</titulo>
            <parrafo>En esta primera unidad ofreceremos...</parrafo>
            <parrafo>En el ámbito de las humanidades y las ciencias sociales...</parrafo>
        </tema>
        <tema n="2">
            <titulo>TEMA 2: Principios fundamentales de un documento XML </titulo>
            <parrafo>En este segundo tema se presentarán los principios fundamentales del lenguaje XML,</parrafo>
            <parrafo>...</parrafo> 
        </tema>
    </contenido>
</curso>
